2.1.1 入门 

In [2]:
import torch

In [6]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x.shape

torch.Size([12])

In [13]:
x.numel()

12

In [14]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [16]:
torch.zeros((2,3,4))
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [17]:
torch.randn(3,4)

tensor([[-1.0360,  0.8000, -0.6395, -0.7535],
        [-0.2432,  0.0107, -2.0408, -0.6919],
        [ 1.1951,  0.5837, -0.1842,  0.3738]])

In [18]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [14]:
import os
os.makedirs(os.path.join(r'C:\Users\25246\Desktop\深度学习入门资料', 'data'), exist_ok= True)
datafile = os.path.join(r'C:\Users\25246\Desktop\深度学习入门资料\data','house_tiny.csv')
with open(datafile, 'w') as f:
    f.write('NumRooms, Alley, Price\n') #列名
    f.write('NA, Pave, 127500\n') #每行表示一个样本数据
    f.write('2,NA, 106000\n')
    f.write('4,NA, 178100\n')
    f.write('NA,NA, 140000\n')

In [15]:
import pandas as pd
data = pd.read_csv(datafile)
print(data)

   NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0    NaN  106000
2       4.0    NaN  178100
3       NaN    NaN  140000


In [16]:
inputs, outputs= data.iloc[:, 0:2],data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  Alley
0       3.0   Pave
1       2.0    NaN
2       4.0    NaN
3       3.0    NaN


Pave视为一个类，NAN视为另一个类。

In [17]:
inputs=pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms   Alley_ Pave   Alley_nan
0       3.0             1           0
1       2.0             0           1
2       4.0             0           1
3       3.0             0           1
