In [2]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [5]:
x.requires_grad_(True) #等价于x = torchi.arange(4.0, requires_grad=True)
x.grad#求导
print(x.grad)

None


In [6]:
#torch.dot() 向量的对应位相乘
y = 2*torch.dot(x,x) 
y

tensor(28., grad_fn=<MulBackward0>)

计算y关于x每个分量的梯度，并打印这些梯度

In [8]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [9]:
x.grad == 4*x

tensor([True, True, True, True])

In [10]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

分离计算

In [11]:
x.grad.zero_()
y = x*x
u = y.detach()
z = u *x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [17]:
x.grad.zero_()
y.sum().backward()
print(y.grad)

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.